import { Inter } from "next/font/google";
import "./globals.css";
import ClientOnlyLayout from './ClientOnlyLayout'; 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ProductivityAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnlyLayout>
          {children}
        </ClientOnlyLayout>
      </body>
    </html>
  );
}
